spring:
  ai:
    openai:
      api-key: sk-proj-TfXcXWEehIvtup8mxseST3BlbkFJLSW9GewqYYyNxMTeguc9
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimension: 1536
  datasource:
    url: jdbc:postgresql://localhost:15438/vectorstore
    username: vectorstore
    password: vectorstore