spring:
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimension: 1536
  datasource:
    url: jdbc:postgresql://localhost:15438/vectorstore
    username: vectorstore
    password: vectorstore

weatherService:
  apiNinjasKey: ${API_NINJAS_KEY}